version: "2.3"

networks:
  test:
    driver: bridge

volumes:
  esdata1:
    driver: local

services:

  es7:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.0
    logging:
      driver: json-file
    container_name: c-es
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - test
    healthcheck:
      test: "curl --fail http://localhost:9200 || exit 1"
      interval: 1s
      timeout: 30s
      retries: 300
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.10.0
    logging:
      driver: json-file
    environment:
      ELASTICSEARCH_HOSTS: http://es7:9200
    container_name: c-kibana
    ports:
      - "5601:5601"
    volumes:
      - ./elasticsearch/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - test
    depends_on:
      es7:
        condition: service_healthy
    restart: unless-stopped
